function varargout=F_seg2(action,varargin)
%% Automatically generated with matlabFunction
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'nargs'
   varargout{1}=2;
   return
  case 'nout'
   varargout{1}=6;
   return
  case 'argrange'
   varargout{1}=struct('x',1:6,'p',7:17);
   return
  case 'argsize'
   varargout{1}=struct('x',6,'p',11);
   return
  case 'vector'
   varargout{1}=struct('x',1,'p',1);
   return
  case 'extension'
   varargout{1}='rhs';
   return
  case 'maxorder'
   varargout{1}=2;
   return
end
nout=6;
order=varargin{1};
f=str2func(sprintf('F_seg2_%s_%d',action,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{2:end});
end



function [out1,out2,out3,out4,out5,out6] = F_seg2_rhs_0(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26,in27,in28,in29,in30,in31,in32,in33,in34)
%F_seg2_rhs_0
%    [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6] = F_seg2_rhs_0(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26,IN27,IN28,IN29,IN30,IN31,IN32,IN33,IN34)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    13-Aug-2025 16:28:08

t2 = -in1;
t3 = in13-1.0;
out1 = in7.*t3.*(in1-in8+in1.*in3);
if nargout > 1
    out2 = in7.*t3.*(in2-in9+in2.*in3.*in10);
end
if nargout > 2
    t4 = in2+t2+1.0;
    out3 = in3.*t3.*t4;
end
if nargout > 3
    t5 = in3.*in6.*t3;
    out4 = t5-in4.*in7.*t3.*(in3+1.0);
end
if nargout > 4
    out5 = -t5-in5.*in7.*t3.*(in3.*in10+1.0);
end
if nargout > 5
    out6 = -in6.*t3.*t4+in4.*in7.*t2.*t3-in2.*in5.*in7.*in10.*t3;
end
end


function [out1,out2,out3,out4,out5,out6] = F_seg2_rhs_1(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26,in27,in28,in29,in30,in31,in32,in33,in34)
%F_seg2_rhs_1
%    [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6] = F_seg2_rhs_1(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26,IN27,IN28,IN29,IN30,IN31,IN32,IN33,IN34)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    13-Aug-2025 16:28:08

t2 = in1.*in3;
t3 = in3.*in10;
t4 = in3+1.0;
t6 = in3.*in6.*in30;
t7 = -in1;
t8 = -in8;
t9 = -in9;
t10 = -in19;
t11 = in13-1.0;
t5 = in2.*t3;
t12 = t3+1.0;
t13 = in18+t10;
t14 = in2+t7+1.0;
t15 = in3.*in23.*t11;
t16 = in6.*in20.*t11;
t17 = in1+t2+t8;
out1 = in7.*t11.*(in18-in25+in1.*in20+in3.*in18)+in7.*in30.*t17+in24.*t11.*t17;
if nargout > 1
    t18 = in2+t5+t9;
    out2 = in7.*t11.*(in19-in26+in19.*t3+in2.*in3.*in27+in2.*in10.*in20)+in7.*in30.*t18+in24.*t11.*t18;
end
if nargout > 2
    out3 = in3.*in30.*t14-in3.*t11.*t13+in20.*t11.*t14;
end
if nargout > 3
    out4 = t6+t15+t16-in4.*in7.*in20.*t11-in4.*in7.*in30.*t4-in4.*in24.*t4.*t11-in7.*in21.*t4.*t11;
end
if nargout > 4
    out5 = -t6-t15-t16-in5.*in7.*in30.*t12-in5.*in24.*t11.*t12-in7.*in22.*t11.*t12-in5.*in7.*t11.*(in3.*in27+in10.*in20);
end
if nargout > 5
    out6 = -in6.*in30.*t14+in6.*t11.*t13-in23.*t11.*t14-in4.*in7.*in18.*t11+in4.*in7.*in30.*t7+in4.*in24.*t7.*t11+in7.*in21.*t7.*t11-in2.*in5.*in7.*in10.*in30-in2.*in5.*in7.*in27.*t11-in2.*in5.*in10.*in24.*t11-in2.*in7.*in10.*in22.*t11+in5.*in7.*in10.*t10.*t11;
end
end


function [out1,out2,out3,out4,out5,out6] = F_seg2_rhs_2(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14,in15,in16,in17,in18,in19,in20,in21,in22,in23,in24,in25,in26,in27,in28,in29,in30,in31,in32,in33,in34)
%F_seg2_rhs_2
%    [OUT1,OUT2,OUT3,OUT4,OUT5,OUT6] = F_seg2_rhs_2(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14,IN15,IN16,IN17,IN18,IN19,IN20,IN21,IN22,IN23,IN24,IN25,IN26,IN27,IN28,IN29,IN30,IN31,IN32,IN33,IN34)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    13-Aug-2025 16:28:08

t2 = in3.*in10;
t3 = in1.*in20;
t4 = in3.*in18;
t5 = in3.*in27;
t6 = in10.*in20;
t7 = in3+1.0;
t11 = -in1;
t12 = -in19;
t13 = -in25;
t14 = -in26;
t15 = in13-1.0;
t17 = in3.*in23.*in30.*2.0;
t18 = in6.*in20.*in30.*2.0;
t8 = in2.*t5;
t9 = in2.*t6;
t10 = in19.*t2;
t16 = t2+1.0;
t19 = in18+t12;
t20 = in2+t11+1.0;
t21 = t5+t6;
t22 = in20.*in23.*t15.*2.0;
t23 = in18+t3+t4+t13;
out1 = in7.*in30.*t23.*2.0+in24.*t15.*t23.*2.0+in24.*in30.*(in1-in8+in1.*in3).*2.0+in7.*in18.*in20.*t15.*2.0;
if nargout > 1
    t24 = in19+t8+t9+t10+t14;
    out2 = in24.*in30.*(in2-in9+in2.*t2).*2.0+in7.*in30.*t24.*2.0+in24.*t15.*t24.*2.0+in7.*t15.*(in19.*t5.*2.0+in19.*t6.*2.0+in2.*in20.*in27.*2.0);
end
if nargout > 2
    out3 = in3.*in30.*t19.*-2.0+in20.*in30.*t20.*2.0-in20.*t15.*t19.*2.0;
end
if nargout > 3
    out4 = t17+t18+t22-in4.*in7.*in20.*in30.*2.0-in4.*in20.*in24.*t15.*2.0-in7.*in20.*in21.*t15.*2.0-in4.*in24.*in30.*t7.*2.0-in7.*in21.*in30.*t7.*2.0-in21.*in24.*t7.*t15.*2.0;
end
if nargout > 4
    out5 = -t17-t18-t22-in5.*in7.*in30.*t21.*2.0-in5.*in24.*in30.*t16.*2.0-in7.*in22.*in30.*t16.*2.0-in5.*in24.*t15.*t21.*2.0-in7.*in22.*t15.*t21.*2.0-in22.*in24.*t15.*t16.*2.0-in5.*in7.*in20.*in27.*t15.*2.0;
end
if nargout > 5
    out6 = in6.*in30.*t19.*2.0-in23.*in30.*t20.*2.0+in23.*t15.*t19.*2.0-in1.*in4.*in24.*in30.*2.0-in1.*in7.*in21.*in30.*2.0-in4.*in7.*in18.*in30.*2.0-in1.*in21.*in24.*t15.*2.0-in4.*in18.*in24.*t15.*2.0-in7.*in18.*in21.*t15.*2.0-in2.*in5.*in7.*in27.*in30.*2.0-in2.*in5.*in10.*in24.*in30.*2.0-in2.*in7.*in10.*in22.*in30.*2.0-in5.*in7.*in10.*in19.*in30.*2.0-in2.*in5.*in24.*in27.*t15.*2.0-in2.*in7.*in22.*in27.*t15.*2.0-in2.*in10.*in22.*in24.*t15.*2.0-in5.*in7.*in19.*in27.*t15.*2.0-in5.*in10.*in19.*in24.*t15.*2.0-in7.*in10.*in19.*in22.*t15.*2.0;
end
end

